### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'driver' in ctera_portal_storage_node

### ISSUE THREAD

**Issue by mgaruccio** [ctera/ctera-ansible-collections#31]
When attempting to run the ctera_portal_storage_node to create a node using the `S3Compatible` bucket type I am getting the error `TypeError: __init__() missing 1 required positional argument: 'driver'`

ful invocation - 

```yaml
    - name: create ctera storage node
      ctera.ctera.ctera_portal_storage_node:
        tenant: "{{ portal_tenant }}"
        ctera_host: "{{ portal_host }}"
        ctera_user: "{{ portal_user }}"
        ctera_password: "{{ portal_password }}"
        ctera_trust_certificate: yes
        state: present
        name: "{{ client_short_name }}_s3-useast1"
        bucket_info:
          bucket_type: S3Compatible
          bucket: "{{ cloudian_bucket }}"
          access_key: "{{ s3_access_key }}"
          secret_key: "{{ s3_secret_key }}"
          endpoint: s3-useast1.expedient.cloud:443
          https: yes
          direct: yes
        dedicated_to: "{{ client_short_name }}"
```

full error - 
```fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    /Users/michaelgaruccio/.local/share/virtualenvs/EEW-Deploy-XQOoyyKX/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.185.235.17'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
      warnings.warn(
    /Users/michaelgaruccio/.local/share/virtualenvs/EEW-Deploy-XQOoyyKX/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.185.235.17'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
      warnings.warn(
    /Users/michaelgaruccio/.local/share/virtualenvs/EEW-Deploy-XQOoyyKX/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.185.235.17'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
      warnings.warn(
    /Users/michaelgaruccio/.local/share/virtualenvs/EEW-Deploy-XQOoyyKX/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.185.235.17'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
      warnings.warn(
    /Users/michaelgaruccio/.local/share/virtualenvs/EEW-Deploy-XQOoyyKX/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.185.235.17'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
      warnings.warn(
    Traceback (most recent call last):
      File "/Users/michaelgaruccio/.ansible/tmp/ansible-tmp-1651385575.4438531-48864-72937461901853/AnsiballZ_ctera_portal_storage_node.py", line 107, in <module>
        _ansiballz_main()
      File "/Users/michaelgaruccio/.ansible/tmp/ansible-tmp-1651385575.4438531-48864-72937461901853/AnsiballZ_ctera_portal_storage_node.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/Users/michaelgaruccio/.ansible/tmp/ansible-tmp-1651385575.4438531-48864-72937461901853/AnsiballZ_ctera_portal_storage_node.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ctera.ctera.plugins.modules.ctera_portal_storage_node', init_globals=dict(_module_fqn='ansible_collections.ctera.ctera.plugins.modules.ctera_portal_storage_node', _modlib_path=modlib_path),
      File "/Users/michaelgaruccio/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/Users/michaelgaruccio/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/Users/michaelgaruccio/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/var/folders/0f/yr7rcvz55yb9fp77rx2l08xc0000gn/T/ansible_ctera.ctera.ctera_portal_storage_node_payload_xm8dli83/ansible_ctera.ctera.ctera_portal_storage_node_payload.zip/ansible_collections/ctera/ctera/plugins/modules/ctera_portal_storage_node.py", line 316, in <module>
      File "/var/folders/0f/yr7rcvz55yb9fp77rx2l08xc0000gn/T/ansible_ctera.ctera.ctera_portal_storage_node_payload_xm8dli83/ansible_ctera.ctera.ctera_portal_storage_node_payload.zip/ansible_collections/ctera/ctera/plugins/modules/ctera_portal_storage_node.py", line 312, in main
      File "/var/folders/0f/yr7rcvz55yb9fp77rx2l08xc0000gn/T/ansible_ctera.ctera.ctera_portal_storage_node_payload_xm8dli83/ansible_ctera.ctera.ctera_portal_storage_node_payload.zip/ansible_collections/ctera/ctera/plugins/module_utils/ctera_portal_base.py", line 50, in run
      File "/var/folders/0f/yr7rcvz55yb9fp77rx2l08xc0000gn/T/ansible_ctera.ctera.ctera_portal_storage_node_payload_xm8dli83/ansible_ctera.ctera.ctera_portal_storage_node_payload.zip/ansible_collections/ctera/ctera/plugins/module_utils/ctera_runner_base.py", line 47, in run
      File "/var/folders/0f/yr7rcvz55yb9fp77rx2l08xc0000gn/T/ansible_ctera.ctera.ctera_portal_storage_node_payload_xm8dli83/ansible_ctera.ctera.ctera_portal_storage_node_payload.zip/ansible_collections/ctera/ctera/plugins/modules/ctera_portal_storage_node.py", line 186, in _execute
      File "/var/folders/0f/yr7rcvz55yb9fp77rx2l08xc0000gn/T/ansible_ctera.ctera.ctera_portal_storage_node_payload_xm8dli83/ansible_ctera.ctera.ctera_portal_storage_node_payload.zip/ansible_collections/ctera/ctera/plugins/modules/ctera_portal_storage_node.py", line 194, in _ensure_present
      File "/var/folders/0f/yr7rcvz55yb9fp77rx2l08xc0000gn/T/ansible_ctera.ctera.ctera_portal_storage_node_payload_xm8dli83/ansible_ctera.ctera.ctera_portal_storage_node_payload.zip/ansible_collections/ctera/ctera/plugins/modules/ctera_portal_storage_node.py", line 198, in _handle_create
      File "/var/folders/0f/yr7rcvz55yb9fp77rx2l08xc0000gn/T/ansible_ctera.ctera.ctera_portal_storage_node_payload_xm8dli83/ansible_ctera.ctera.ctera_portal_storage_node_payload.zip/ansible_collections/ctera/ctera/plugins/modules/ctera_portal_storage_node.py", line 206, in _make_bucket_obj
    TypeError: __init__() missing 1 required positional argument: 'driver'
  module_stdout: |-
    2022-05-01 02:12:55,772    INFO [login.py:19] [login] - User logged in. {'host': '10.185.235.17', 'user': 'admin'}
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

I was actually able to resolve the problem by adding an additional string parameter to the `bucket_info` object to have it take a new `driver` property and just passing it a value of `GenericS3` in my playbook.  I'm including that below, although I assume it's not the correct solution here.

```python
def __init__(self):
        super().__init__(
            dict(
                state=dict(choices=['present', 'absent'], default='present'),
                name=dict(required=True),
                bucket_info=dict(type='dict', options=dict(
                    bucket_type=dict(required=True, choices=['Azure', 'Scality', 'AWS', 'ICOS',
                                                             'S3Compatible', 'Nutanix', 'Wasabi', 'Google', 'NetAppStorageGRID', 'GenericS3']),
                    bucket=dict(required=True),
                    access_key=dict(required=True, no_log=True),
                    secret_key=dict(required=True, no_log=True),
                    endpoint=dict(),
                    https=dict(type='bool'),
                    direct=dict(type='bool'),
                    driver=dict(type='str')
                )),
                read_only=dict(type='bool', default=False),
                dedicated_to=dict(),
            )
        )
```

and the resulting, working, task
```yaml
    - name: create ctera storage node
      ctera.ctera.ctera_portal_storage_node:
        tenant: "{{ portal_tenant }}"
        ctera_host: "{{ portal_host }}"
        ctera_user: "{{ portal_user }}"
        ctera_password: "{{ portal_password }}"
        ctera_trust_certificate: yes
        state: present
        name: "{{ client_short_name }}_s3-useast1"
        bucket_info:
          bucket_type: S3Compatible
          bucket: "{{ cloudian_bucket }}"
          access_key: "{{ s3_access_key }}"
          secret_key: "{{ s3_secret_key }}"
          endpoint: s3-useast1.expedient.cloud:443
          https: yes
          direct: yes
          driver: GenericS3
        dedicated_to: "{{ client_short_name }}"
```

**Comment by Elchay-Levy** [comment]
@mgaruccio Hi, sorry for the long wait, 
I fixed that problem, S3Compatible is not a BucketType so I changed it to GenericS3,
#33 
please update `ctera-ansible-collections` to the latest version.
and also need to update `cterasdk` package to the latest version
[https://github.com/ctera/ctera-python-sdk/releases/tag/2.18.24](url)
